// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhcypgxdmnbaoaihnxyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoY3lwZ3hkbW5iYW9haWhueHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3Njg4OTgsImV4cCI6MjA2MjM0NDg5OH0.xnj8mrYZIyzB0hNHRIXdPukmjD5ZTTHFh5Zw2YNRI3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);